using System.ComponentModel;
using System.Collections.Concurrent;
using System.Diagnostics;
using CodeReviewAgent.Agents;
using CodeReviewAgent.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.AI;

namespace CodeReviewAgent.Services;

/// <summary>
/// Orchestrates code review by routing files to appropriate language-specific agents
/// using Microsoft.Agents.AI multi-agent coordination
/// </summary>
public class CodeReviewOrchestrator
{
    private readonly ILogger<CodeReviewOrchestrator> _logger;
    private readonly IChatClient _chatClient;
    private readonly Dictionary<string, ILanguageReviewAgent> _agents;
    private readonly Dictionary<string, string> _extensionToLanguage;

    // File name suffixes that indicate auto-generated code (case-insensitive)
    private static readonly string[] GeneratedFileSuffixes =
    [
        ".g.cs", ".g.i.cs", ".designer.cs",
        ".generated.cs", ".generated.ts", ".generated.js",
        "_generated.cs", "_generated.ts", "_generated.go", "_generated.js",
        "_gen.cs", "_gen.ts", "_gen.go",
        ".pb.cs", ".pb.go", ".pb.h", ".pb.cc",
        ".min.js", ".min.css",
        ".snap",     // Jest snapshots
    ];

    // Exact file names to always skip
    private static readonly HashSet<string> GeneratedFileNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
        "go.sum", "Cargo.lock",
    };

    // Path segments — any file under these directories is skipped
    private static readonly string[] GeneratedPathSegments =
    [
        "/obj/", "\\obj\\", "/bin/", "\\bin\\",
        "/Migrations/", "\\Migrations\\",
    ];

    // Content header prefixes that signal auto-generated files (checked against first 8 lines)
    private static readonly string[] GeneratedContentPrefixes =
    [
        "// <auto-generated",
        "// This code was generated",
        "// Auto-generated",
        "// Generated by",
        "// <autogenerated",
        "/* auto-generated",
        "/* generated by",
        "# this file is auto-generated",
        "# generated by",
        "# do not edit",
        "# auto-generated",
        "// do not edit",
        "/* do not edit",
    ];

    public CodeReviewOrchestrator(
        ILogger<CodeReviewOrchestrator> logger,
        IChatClient chatClient,
        IEnumerable<ILanguageReviewAgent> agents)
    {
        _logger = logger;
        _chatClient = chatClient; // Used for general reviews when no specialized agent exists
        _agents = agents.ToDictionary(a => a.Language, a => a);
        _extensionToLanguage = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        // Build extension to language mapping
        foreach (var agent in agents)
        {
            foreach (var ext in agent.FileExtensions)
            {
                _extensionToLanguage[ext] = agent.Language;
            }
        }

        // No plugin registration needed - manual routing
        _logger.LogInformation("Registered {AgentCount} language review agents: {Languages}",
            _agents.Count, string.Join(", ", _agents.Keys));
    }

    private static bool IsGeneratedFile(PullRequestFile file)
    {
        var fileName = Path.GetFileName(file.Path);

        // Exact name match
        if (GeneratedFileNames.Contains(fileName))
            return true;

        // Suffix match (e.g. Foo.g.cs, styles.min.css)
        foreach (var suffix in GeneratedFileSuffixes)
        {
            if (fileName.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        // Path segment match (e.g. /Migrations/, /obj/)
        foreach (var segment in GeneratedPathSegments)
        {
            if (file.Path.Contains(segment, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        // Content header match — check first 8 lines for auto-generated markers
        if (!string.IsNullOrEmpty(file.Content))
        {
            var reader = new StringReader(file.Content);
            for (var i = 0; i < 8; i++)
            {
                var line = reader.ReadLine();
                if (line == null) break;
                var trimmed = line.TrimStart();
                foreach (var prefix in GeneratedContentPrefixes)
                {
                    if (trimmed.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                        return true;
                }
            }
        }

        return false;
    }

    /// <summary>
    /// Review files by orchestrating language-specific agents
    /// </summary>
    public async Task<List<CodeReviewComment>> ReviewFilesAsync(
        List<PullRequestFile> files,
        string codebaseContext)
    {
        _logger.LogInformation("╔════════════════════════════════════════════════════════════╗");
        _logger.LogInformation("║ FILE PROCESSING STRATEGY                                   ║");
        _logger.LogInformation("╚════════════════════════════════════════════════════════════╝");
        _logger.LogInformation("📂 Processing {FileCount} files in PARALLEL for faster reviews", files.Count);
        _logger.LogInformation("   Each file gets its own RAG context and LLM call");
        _logger.LogInformation("   Files: {Files}", string.Join(", ", files.Select(f => Path.GetFileName(f.Path))));
        
        var overallStopwatch = System.Diagnostics.Stopwatch.StartNew();
        var failures = new ConcurrentBag<string>();
        
        // Process files in parallel for faster reviews
        var reviewTasks = files.Select(async file =>
        {
            try
            {
                if (IsGeneratedFile(file))
                {
                    _logger.LogInformation("⏭️  Skipping generated/lock file: {FilePath}", file.Path);
                    return new List<CodeReviewComment>();
                }

                var extension = Path.GetExtension(file.Path);

                if (string.IsNullOrEmpty(extension))
                {
                    _logger.LogWarning("Skipping file without extension: {FilePath}", file.Path);
                    return new List<CodeReviewComment>();
                }

                // Determine which agent should review this file
                if (_extensionToLanguage.TryGetValue(extension, out var language) &&
                    _agents.TryGetValue(language, out var agent))
                {
                    _logger.LogInformation("Routing {FilePath} to {Language} agent — 3 focused passes", file.Path, language);
                    return await RunFocusedPassesAsync(agent, file, codebaseContext);
                }
                else
                {
                    _logger.LogInformation("No specialized agent for {Extension}, using general review for {FilePath}",
                        extension, file.Path);
                    return await ReviewWithGeneralAgentAsync(file, codebaseContext);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error reviewing file {FilePath}", file.Path);
                failures.Add($"{file.Path}: {ex.Message}");
                return new List<CodeReviewComment>();
            }
        });

        var results = await Task.WhenAll(reviewTasks);
        overallStopwatch.Stop();

        var allComments = results.SelectMany(comments => comments).ToList();

        _logger.LogInformation("╔════════════════════════════════════════════════════════════╗");
        _logger.LogInformation("║ PARALLEL PROCESSING COMPLETE                              ║");
        _logger.LogInformation("╚════════════════════════════════════════════════════════════╝");
        _logger.LogInformation("⏱️  Total parallel processing time: {TotalMs}ms ({TotalSec:F2} seconds)",
            overallStopwatch.ElapsedMilliseconds, overallStopwatch.Elapsed.TotalSeconds);
        _logger.LogInformation("📊 Processing results:");
        _logger.LogInformation("   Files processed: {FileCount}", files.Count);
        _logger.LogInformation("   Total comments generated: {CommentCount}", allComments.Count);
        _logger.LogInformation("   Average time per file: {AvgMs}ms",
            files.Count > 0 ? overallStopwatch.ElapsedMilliseconds / files.Count : 0);

        if (!failures.IsEmpty)
        {
            _logger.LogWarning("   Files with review errors: {FailureCount}", failures.Count);
        }

        _logger.LogInformation("════════════════════════════════════════════════════════════");

        if (!failures.IsEmpty && allComments.Count == 0)
        {
            var errorDetails = string.Join(" | ", failures.Take(3));
            throw new InvalidOperationException(
                $"Code review failed for all files. {errorDetails}. Check LLM chat credentials/configuration and retry.");
        }

        // Cross-file analysis — only worth running when there are multiple changed files
        var reviewableFiles = files.Where(f => !IsGeneratedFile(f) && !string.IsNullOrEmpty(Path.GetExtension(f.Path))).ToList();
        if (reviewableFiles.Count > 1)
        {
            var crossFileComments = await RunCrossFileAnalysisAsync(reviewableFiles, codebaseContext);
            if (crossFileComments.Count > 0)
            {
                _logger.LogInformation("🔗 Cross-file analysis added {Count} additional comments", crossFileComments.Count);
                allComments.AddRange(crossFileComments);
            }
        }

        return allComments;
    }

    /// <summary>
    /// Runs security, bugs, and performance passes in parallel then merges results.
    /// Duplicate detections (same startLine + type from multiple passes) are collapsed
    /// by keeping the comment with the highest confidence.
    /// </summary>
    private async Task<List<CodeReviewComment>> RunFocusedPassesAsync(
        ILanguageReviewAgent agent,
        PullRequestFile file,
        string codebaseContext)
    {
        var passes = new[]
        {
            Agents.FocusPassHelper.Security,
            Agents.FocusPassHelper.Bugs,
            Agents.FocusPassHelper.Performance,
        };

        var passTasks = passes.Select(focus => agent.ReviewFileAsync(file, codebaseContext, focus));
        var passResults = await Task.WhenAll(passTasks);

        for (var i = 0; i < passes.Length; i++)
            _logger.LogInformation("   Pass [{Focus}]: {Count} comments", passes[i], passResults[i].Count);

        var merged = MergeAndDedup(passResults.SelectMany(r => r));
        _logger.LogInformation("   Merged total: {Count} unique comments for {FilePath}", merged.Count, file.Path);
        return merged;
    }

    /// <summary>
    /// Collapses comments with the same (FilePath, StartLine, CommentType) key,
    /// keeping the highest-confidence one per group.
    /// </summary>
    private static List<CodeReviewComment> MergeAndDedup(IEnumerable<CodeReviewComment> comments)
    {
        return comments
            .GroupBy(c => (c.FilePath, c.StartLine, c.CommentType))
            .Select(g => g.OrderByDescending(c => c.Confidence).ThenByDescending(c => SeverityRank(c.Severity)).First())
            .OrderBy(c => c.StartLine)
            .ToList();
    }

    private static int SeverityRank(string? severity) => severity?.ToLower() switch
    {
        "critical" => 4,
        "high"     => 3,
        "medium"   => 2,
        "low"      => 1,
        _          => 0
    };

    /// <summary>
    /// Runs a single LLM pass across all changed file diffs together to find
    /// cross-file consistency issues: renamed constants not updated in callers,
    /// new config keys missing from YAML, interface changes without implementation
    /// updates, missing test coverage for newly added methods, etc.
    /// </summary>
    private async Task<List<CodeReviewComment>> RunCrossFileAnalysisAsync(
        List<PullRequestFile> files,
        string codebaseContext)
    {
        const int MaxDiffCharsPerFile = 3_000;

        try
        {
            _logger.LogInformation("🔗 Starting cross-file analysis across {FileCount} files", files.Count);

            var sb = new System.Text.StringBuilder();
            sb.AppendLine("The following files were all changed together in one pull request.");
            sb.AppendLine("Each file's unified diff is shown below.");
            sb.AppendLine();

            foreach (var file in files)
            {
                sb.AppendLine($"### {file.Path} ({file.ChangeType})");
                var diff = file.UnifiedDiff ?? file.Content ?? string.Empty;
                if (diff.Length > MaxDiffCharsPerFile)
                    diff = diff[..MaxDiffCharsPerFile] + "\n[truncated]";
                sb.AppendLine("```diff");
                sb.AppendLine(diff);
                sb.AppendLine("```");
                sb.AppendLine();
            }

            var fileList = string.Join(", ", files.Select(f => f.Path));

            var prompt = $$$"""
                You are a senior code reviewer performing a CROSS-FILE consistency analysis.
                Your job is to find issues that ONLY become visible when looking at multiple changed files together.

                Changed files in this PR:
                {{{fileList}}}

                {{{sb}}}

                Codebase Context:
                {{{codebaseContext}}}

                CROSS-FILE ISSUES TO LOOK FOR:
                1. **Renamed/removed constants or types** used in one changed file but not updated in another changed file
                2. **New config keys or settings** added in a C# config class but missing from the corresponding YAML/JSON settings file (or vice versa)
                3. **Interface or API changes** in one file whose callers in other changed files are not updated
                4. **New public methods or behaviours** added in a source file but not covered by tests in the corresponding test file
                5. **Inconsistent values** — the same literal value hardcoded differently across multiple changed files that should share a constant
                6. **Missing paired changes** — e.g. a feature flag added in code but not in the feature flag config file

                IMPORTANT RULES:
                - ONLY report issues that require looking at MORE THAN ONE file to detect. Do not repeat single-file issues.
                - For each issue, set "filePath" to the file that should receive the comment (the one missing the update, or the most relevant file).
                - Set startLine/endLine to the relevant line numbers in that file (use 1 if the issue is file-level with no specific line).
                - Be conservative — only report issues you are confident about (confidence >= 0.7).

                Return a JSON array (empty array [] if no cross-file issues found):
                [
                  {
                    "filePath": "path/to/file.cs",
                    "startLine": 42,
                    "endLine": 42,
                    "severity": "high",
                    "type": "issue",
                    "comment": "Clear explanation referencing both files involved",
                    "suggestedFix": "Concrete fix",
                    "confidence": 0.85
                  }
                ]
                """;

            var messages = new List<ChatMessage>
            {
                new(ChatRole.System, "You are a senior code reviewer specialising in cross-file consistency analysis."),
                new(ChatRole.User, prompt)
            };

            _logger.LogInformation("📤 Cross-file analysis prompt: {Chars} chars across {Files} files", prompt.Length, files.Count);

            var stopwatch = Stopwatch.StartNew();
            var response = await _chatClient.GetResponseAsync(messages);
            stopwatch.Stop();

            var responseText = response.Text ?? "[]";
            _logger.LogInformation("📥 Cross-file analysis response: {Chars} chars in {Ms}ms", responseText.Length, stopwatch.ElapsedMilliseconds);
            _logger.LogInformation("📝 Cross-file LLM response:\n{Response}", responseText);

            return ParseCrossFileComments(responseText, files);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error in cross-file analysis");
            return [];
        }
    }

    private List<CodeReviewComment> ParseCrossFileComments(string jsonResponse, List<PullRequestFile> files)
    {
        try
        {
            jsonResponse = ExtractJsonPayload(jsonResponse);
            var validPaths = new HashSet<string>(files.Select(f => f.Path), StringComparer.OrdinalIgnoreCase);

            var options = new System.Text.Json.JsonSerializerOptions { PropertyNameCaseInsensitive = true };
            var parsed = System.Text.Json.JsonSerializer.Deserialize<List<CrossFileCommentJson>>(jsonResponse, options)
                ?? [];

            var comments = new List<CodeReviewComment>();
            foreach (var c in parsed)
            {
                var filePath = c.FilePath ?? string.Empty;

                // Accept exact match or longest suffix match against known file paths
                if (!validPaths.Contains(filePath))
                {
                    filePath = files.Select(f => f.Path)
                        .FirstOrDefault(p => p.EndsWith(filePath.TrimStart('/'), StringComparison.OrdinalIgnoreCase))
                        ?? filePath;
                }

                var confidence = c.Confidence is > 0.0 and <= 1.0 ? c.Confidence : 1.0;
                if (confidence < 0.7) continue;

                var sl = c.StartLine > 0 ? c.StartLine : 1;
                comments.Add(new CodeReviewComment
                {
                    FilePath = filePath,
                    StartLine = sl,
                    EndLine = c.EndLine >= sl ? c.EndLine : sl,
                    Severity = c.Severity?.ToLower() ?? "medium",
                    CommentType = c.Type?.ToLower() ?? "issue",
                    CommentText = $"[Cross-file] {c.Comment ?? string.Empty}",
                    SuggestedFix = c.SuggestedFix ?? string.Empty,
                    Confidence = confidence
                });
            }

            _logger.LogInformation("✅ Cross-file analysis: {Count} comments after confidence filter", comments.Count);
            return comments;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error parsing cross-file analysis response");
            return [];
        }
    }

    private class CrossFileCommentJson
    {
        public string? FilePath { get; set; }
        public int StartLine { get; set; }
        public int EndLine { get; set; }
        public string? Severity { get; set; }
        public string? Type { get; set; }
        public string? Comment { get; set; }
        public string? SuggestedFix { get; set; }
        public double Confidence { get; set; }
    }

    /// <summary>
    /// General review for files without specialized agents
    /// </summary>
    private async Task<List<CodeReviewComment>> ReviewWithGeneralAgentAsync(
        PullRequestFile file,
        string codebaseContext)
    {
        try
        {
            // Cap content to avoid context length errors. For large/generated files, prefer the diff.
            const int MAX_CONTENT_CHARS = 40_000;
            var isLargeFile = (file.Content?.Length ?? 0) > MAX_CONTENT_CHARS;
            var contentSection = isLargeFile
                ? $"[File is large ({file.Content!.Length:N0} chars). Showing diff only — full content truncated to avoid context limits.]\n\nDiff:\n```\n{file.UnifiedDiff}\n```"
                : $"```\n{file.Content}\n```";

            // Omit previous content for large files (the diff captures what changed)
            var previousSection = (!isLargeFile && !string.IsNullOrEmpty(file.PreviousContent))
                ? $"Previous Content:\n```\n{file.PreviousContent}\n```\n"
                : string.Empty;

            var prompt = $$$"""
                You are a general code reviewer with broad knowledge of software engineering best practices.

                Review the following file that was changed in a pull request:

                File Path: {{{file.Path}}}
                Change Type: {{{file.ChangeType}}}

                Current Content:
                {{{contentSection}}}

                {{{previousSection}}}
                Codebase Context:
                {{{codebaseContext}}}

                Provide a code review focusing on:
                1. Security vulnerabilities
                2. Potential bugs and logic errors
                3. Code quality and maintainability
                4. Best practices

                For each issue found, provide:
                - Line number (if applicable)
                - Severity (high/medium/low)
                - Type (issue/suggestion/nitpick)
                - Clear explanation and recommendation

                Return your response as a JSON array of objects with this structure:
                [
                  {
                    "lineNumber": 10,
                    "severity": "high",
                    "type": "issue",
                    "comment": "Detailed explanation and recommendation"
                  }
                ]

                If no issues are found, return an empty array: []
                """;

            var messages = new List<ChatMessage>
            {
                new(ChatRole.System, "You are a general code reviewer with broad knowledge of software engineering best practices."),
                new(ChatRole.User, prompt)
            };

            // Log LLM request details
            _logger.LogInformation("╔════════════════════════════════════════════════════════════╗");
            _logger.LogInformation("║ LLM REQUEST: General Code Review                           ║");
            _logger.LogInformation("╚════════════════════════════════════════════════════════════╝");
            _logger.LogInformation("📤 SENDING TO LLM:");
            _logger.LogInformation("   File: {FilePath}", file.Path);
            _logger.LogInformation("   System prompt length: {Length} chars", messages[0].Text?.Length ?? 0);
            _logger.LogInformation("   User prompt length: {Length} chars", prompt.Length);
            _logger.LogInformation("   Total prompt length: {Length} chars", (messages[0].Text?.Length ?? 0) + prompt.Length);
            _logger.LogInformation("   Codebase context included: {HasContext}", !string.IsNullOrEmpty(codebaseContext));
            _logger.LogInformation("📝 FULL USER PROMPT:\n{Prompt}", prompt);

            var stopwatch = Stopwatch.StartNew();
            ChatResponse response = await _chatClient.GetResponseAsync(messages);
            stopwatch.Stop();

            var responseText = response.Text ?? "[]";

            // Log LLM response details
            _logger.LogInformation("╔════════════════════════════════════════════════════════════╗");
            _logger.LogInformation("║ LLM RESPONSE: General Code Review                          ║");
            _logger.LogInformation("╚════════════════════════════════════════════════════════════╝");
            _logger.LogInformation("📥 RECEIVED FROM LLM:");
            _logger.LogInformation("   Response length: {Length} chars", responseText.Length);
            _logger.LogInformation("   ⏱️  Time taken: {ElapsedMs} ms ({ElapsedSec:F2} seconds)",
                stopwatch.ElapsedMilliseconds, stopwatch.Elapsed.TotalSeconds);

            // Log token usage if available
            if (response.Usage != null)
            {
                _logger.LogInformation("📊 TOKEN USAGE:");
                _logger.LogInformation("   Input tokens: {InputTokens}", response.Usage.InputTokenCount ?? 0);
                _logger.LogInformation("   Output tokens: {OutputTokens}", response.Usage.OutputTokenCount ?? 0);
                _logger.LogInformation("   Total tokens: {TotalTokens}",
                    (response.Usage.InputTokenCount ?? 0) + (response.Usage.OutputTokenCount ?? 0));

                // Estimate cost (approximate pricing for GPT-4)
                var inputCost = (response.Usage.InputTokenCount ?? 0) * 0.00003m; // $0.03 per 1K input
                var outputCost = (response.Usage.OutputTokenCount ?? 0) * 0.00006m; // $0.06 per 1K output
                _logger.LogInformation("   💰 Estimated cost: ${TotalCost:F4} (input: ${InputCost:F4}, output: ${OutputCost:F4})",
                    inputCost + outputCost, inputCost, outputCost);
            }
            else
            {
                _logger.LogInformation("📊 TOKEN USAGE: Not available from response");
            }

            _logger.LogInformation("📝 FULL LLM RESPONSE:\n{Response}", responseText);
            _logger.LogInformation("════════════════════════════════════════════════════════════");

            return ParseReviewComments(responseText, file.Path);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error in general review for {FilePath}", file.Path);
            return new List<CodeReviewComment>();
        }
    }

    private List<CodeReviewComment> ParseReviewComments(string jsonResponse, string filePath)
    {
        try
        {
            jsonResponse = ExtractJsonPayload(jsonResponse);

            var options = new System.Text.Json.JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };

            var parsedComments = System.Text.Json.JsonSerializer.Deserialize<List<ReviewCommentJson>>(jsonResponse, options)
                ?? new List<ReviewCommentJson>();

            return parsedComments.Select(c => new CodeReviewComment
            {
                FilePath = filePath,
                StartLine = c.LineNumber,
                EndLine = c.LineNumber,
                Severity = c.Severity?.ToLower() ?? "low",
                CommentType = c.Type?.ToLower() ?? "suggestion",
                CommentText = c.Comment ?? string.Empty
            }).ToList();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error parsing review comments JSON. Response preview: {Preview}",
                jsonResponse.Length > 500 ? jsonResponse.Substring(0, 500) : jsonResponse);
            return new List<CodeReviewComment>();
        }
    }

    private static string ExtractJsonPayload(string response)
    {
        var trimmed = response.Trim();
        if (trimmed.StartsWith("```json"))
        {
            trimmed = trimmed.Substring(7);
        }

        if (trimmed.StartsWith("```"))
        {
            trimmed = trimmed.Substring(3);
        }

        if (trimmed.EndsWith("```"))
        {
            trimmed = trimmed.Substring(0, trimmed.Length - 3);
        }

        trimmed = trimmed.Trim();

        // Most responses should be an array. If the model adds leading or trailing text,
        // extract only the first complete JSON array segment.
        var firstArray = trimmed.IndexOf('[');
        var lastArray = trimmed.LastIndexOf(']');
        if (firstArray >= 0 && lastArray > firstArray)
        {
            return trimmed.Substring(firstArray, lastArray - firstArray + 1);
        }

        // Some models wrap the output as { "comments": [ ... ] }.
        try
        {
            using var doc = System.Text.Json.JsonDocument.Parse(trimmed);
            if (doc.RootElement.ValueKind == System.Text.Json.JsonValueKind.Object &&
                doc.RootElement.TryGetProperty("comments", out var comments) &&
                comments.ValueKind == System.Text.Json.JsonValueKind.Array)
            {
                return comments.GetRawText();
            }
        }
        catch
        {
            // Let the caller attempt normal deserialize and surface the parse failure in logs.
        }

        return trimmed;
    }

    private class ReviewCommentJson
    {
        public int LineNumber { get; set; }
        public string? Severity { get; set; }
        public string? Type { get; set; }
        public string? Comment { get; set; }
    }
}
